=head1 NAME

Graph::Undirected::Hamiltonicity::Wolfram - determine the Hamiltonicity of a given graph using the Wolfram Cloud.

=head1 VERSION

Version 0.01

=head1 SYNOPSIS

    use Graph::Undirected::Hamiltonicity::Wolfram;

    my $result;
    eval {
        # $g is a Graph::Undirected
        $result = is_hamiltonian_per_wolfram( $g );
    };
    warn $@ if $@;

   if ( $result ) {
       print "Graph is Hamiltonian.\n";
   } else {
       print "Graph is not Hamiltonian.\n";
   }


=head1 EXPORT

The is_hamiltonian_per_wolfram() subroutine is exported by default.

=back

=head1 SUBROUTINES

=head2 is_hamiltonian_per_wolfram

Takes: a Graph::Undirected

Returns: 1     if the graph is Hamiltonian
         0     if the graph is non-Hamiltonian

Throws: an exception if an error is encountered.

=head1 AUTHOR

Ashwin Dixit, C<< <ashwin at ownlifeful dot com> >>


=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Graph::Undirected::Hamiltonicity::Wolfram

=cut

